### ISSUE TITLE
Add color to git-status-mini

### ISSUE THREAD

**Issue by pgriepen** [jrockway/ibuffer-git#1]
Nicely done.  How about adding color to git-status-mini?  The patch below, uses your faces & works for me.

```
diff --git a/ibuffer-git.el b/ibuffer-git.el
index 3677be5..c7fb5c5 100644
--- a/ibuffer-git.el
+++ b/ibuffer-git.el
@@ -112,8 +112,8 @@ Argument EVENT is the mouse event that triggered us."
                            (ibuffer-git-check-status (buffer-file-name))))
           (cons 0 0))
     (cond ((= 0 (+ a d)) " ")
-          ((< a d) "-")
-          ((>= a d) "+"))))
+          ((< a d) (propertize "-" 'face 'ibuffer-git-del-face))
+          ((>= a d) (propertize "+" 'face 'ibuffer-git-add-face)))))

 (provide 'ibuffer-git)
 ;;; ibuffer-git.el ends here
```

**Comment by jrockway** [comment]
Thanks.  Can you please fork the repository, commit, push, and send a pull request?  This will allow me to cherry-pick your commit and maintain the authorship information, which can be important if ibuffer-git were to become part of the Emacs core.  Also, credit where credit is due!

Normally I would just add this for you, but your github page is sparse with respect to personal information :)
